package ru.job4j.tracker;

/**
 * Class Item.
 *
 * @author Vladimir Ivanov
 * @version 0.1
 * @since 12.08.2017
 */
public class Item {

    /**
     * Unique item ID (auto-generated by Tracker).
     */
    private String id;

    /**
     * Item name (given during creation).
     */
    private String name;

    /**
     * Item description (given during creation).
     */
    private String desc;

    /**
     * Creation timestamp in milliseconds (auto-assigned in constructor).
     */
    private long created;

    /**
     * Item comments. Optional field.
     */
    private String[] comments;

    /**
     * Item constructor.
     *
     * @param name     Short name
     * @param desc     Detailed description
     * @param comments Comments
     */
    public Item(String name, String desc, String[] comments) {
        this.name = name;
        this.desc = desc;
        this.comments = comments;
    }

    /**
     * Item constructor without comments.
     *
     * @param name Short name
     * @param desc Detailed description
     */
    public Item(String name, String desc) {
        this(name, desc, new String[]{});
    }

    /**
     * ID getter.
     *
     * @return Item ID
     */
    public String getId() {

        return id;
    }

    /**
     * Item ID setter.
     *
     * @param id New value of ID
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Name getter.
     *
     * @return Item name
     */
    public String getName() {
        return name;
    }

    /**
     * Item name setter.
     *
     * @param name New item name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Item description getter.
     *
     * @return Item description
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Item description setter.
     *
     * @param desc New item description
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * Item comments getter.
     *
     * @return Array with item comments
     */
    public String[] getComments() {
        return comments;
    }

    /**
     * Item comments setter.
     *
     * @param comments New item comments
     */
    public void setComments(String[] comments) {
        this.comments = comments;
    }

    /**
     * Item pretty print.
     *
     * @return String representation of item
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("    id: %s", this.id)).append(System.lineSeparator());
        sb.append(String.format("  name: %s", this.name)).append(System.lineSeparator());
        sb.append(String.format("  desc: %s", this.desc)).append(System.lineSeparator());
        sb.append(String.format("  comments (%d):", this.comments.length));
        for (int i = 0; i < this.comments.length; i++) {
            sb.append(System.lineSeparator()).append(String.format("%6d) %s", i, this.comments[i]));
        }
        return sb.toString();
    }
}
