package ru.job4j.tracker;

import java.util.ArrayList;
import java.util.List;

/**
 * Class Item.
 *
 * @author Vladimir Ivanov
 * @version 0.2
 * @since 22.08.2017
 */
public class Item {
    /**
     * Unique item ID (auto-generated by Tracker).
     */
    private String id;

    /**
     * Item name (given during creation).
     */
    private String name;

    /**
     * Item description (given during creation).
     */
    private String desc;

    /**
     * Item comments. Optional field.
     */
    private List<String> comments;

    /**
     * Item constructor.
     *
     * @param name    Short name
     * @param desc    Detailed description
     * @param comment Initial comment
     */
    public Item(String name, String desc, String comment) {
        this.name = name;
        this.desc = desc;
        this.comments = new ArrayList<>();
        if (comment != null) {
            this.comments.add(comment);
        }
    }

    /**
     * Item constructor without comment.
     *
     * @param name Short name
     * @param desc Detailed description
     */
    public Item(String name, String desc) {
        this(name, desc, null);
    }

    /**
     * ID getter.
     *
     * @return Item ID
     */
    public String getId() {

        return id;
    }

    /**
     * Item ID setter.
     *
     * @param id New value of ID
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Name getter.
     *
     * @return Item name
     */
    public String getName() {
        return name;
    }

    /**
     * Item name setter.
     *
     * @param name New item name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Item description getter.
     *
     * @return Item description
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Item description setter.
     *
     * @param desc New item description
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * Item comments getter.
     *
     * @return Array with item comments
     */
    public List<String> getComments() {
        return comments;
    }

    /**
     * Add comment.
     *
     * @param comment New item comment
     */
    public void addComment(String comment) {
        this.comments.add(comment);
    }

    /**
     * Item pretty print.
     *
     * @return String representation of item
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("    id: %s", this.id)).append(System.lineSeparator());
        sb.append(String.format("  name: %s", this.name)).append(System.lineSeparator());
        sb.append(String.format("  desc: %s", this.desc)).append(System.lineSeparator());
        sb.append(String.format("  comments (%d):", this.comments.size()));
        for (int index = 0; index < this.comments.size(); index++) {
            sb.append(System.lineSeparator()).append(String.format("%6d) %s", index, this.comments.get(index)));
        }
        return sb.toString();
    }
}
